--------------------------------------------------------
--  DDL for Table SOK_USER
--------------------------------------------------------

  CREATE TABLE "SOK_USER" 
   (	"USER_ID" NUMBER(*,0), 
	"USER_FIRSTNAME" VARCHAR2(80 BYTE), 
	"USER_LASTNAME" VARCHAR2(80 BYTE), 
	"USER_EMAIL" VARCHAR2(80 BYTE), 
	"USER_PASSWORD" VARCHAR2(30 BYTE), 
	"USER_PHONE" NUMBER(*,0), 
	"USER_INVOICING_ADDRESS" VARCHAR2(240 BYTE), 
	"USER_DELIVERY_ADDRESS" VARCHAR2(240 BYTE), 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(80 BYTE), 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(80 BYTE)
   ) ;
