--------------------------------------------------------
--  Constraints for Table SOK_ROLE_LU
--------------------------------------------------------

  ALTER TABLE "SOK_ROLE_LU" ADD CONSTRAINT "SOK_ROLE_UK" UNIQUE ("ROLE_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_ROLE_LU" ADD CONSTRAINT "SOK_ROLE_PK" PRIMARY KEY ("ROLE_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_ROLE_LU" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_ROLE_LU" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_ROLE_LU" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_ROLE_LU" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_ROLE_LU" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOK_ROLE_LU" MODIFY ("ROLE_CODE" NOT NULL ENABLE);
