--------------------------------------------------------
--  Constraints for Table SOK_ORDER_STATUS_LU
--------------------------------------------------------

  ALTER TABLE "SOK_ORDER_STATUS_LU" ADD CONSTRAINT "SOK_ORDER_STATUS_UK" UNIQUE ("ORDER_STATUS_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_ORDER_STATUS_LU" ADD CONSTRAINT "SOK_ORDER_STATUS_PK" PRIMARY KEY ("ORDER_STATUS_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_ORDER_STATUS_LU" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER_STATUS_LU" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER_STATUS_LU" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER_STATUS_LU" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER_STATUS_LU" MODIFY ("ORDER_STATUS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER_STATUS_LU" MODIFY ("ORDER_STATUS_CODE" NOT NULL ENABLE);
