--------------------------------------------------------
--  Constraints for Table SOK_PRODUCT_LU
--------------------------------------------------------

  ALTER TABLE "SOK_PRODUCT_LU" ADD CONSTRAINT "SOK_PRODUCT_UK" UNIQUE ("PRODUCT_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_PRODUCT_LU" ADD CONSTRAINT "SOK_PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_PRODUCT_LU" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_LU" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_LU" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_LU" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_LU" MODIFY ("PRODUCT_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_LU" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_LU" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
