--------------------------------------------------------
--  Constraints for Table SOK_ORDER
--------------------------------------------------------

  ALTER TABLE "SOK_ORDER" ADD CONSTRAINT "SOK_ORDER_PK" PRIMARY KEY ("ORDER_ID") USING INDEX ENABLE;
  ALTER TABLE "SOK_ORDER" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER" MODIFY ("ORDER_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER" MODIFY ("ORDER_ID" NOT NULL ENABLE);
