--------------------------------------------------------
--  Constraints for Table SOK_SIZE_RANGE_LU
--------------------------------------------------------

  ALTER TABLE "SOK_SIZE_RANGE_LU" ADD CONSTRAINT "SOK_SIZE_RANGE_UK" UNIQUE ("SIZE_LOWER_VALUE", "SIZE_HIGHER_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_SIZE_RANGE_LU" ADD CONSTRAINT "SOK_SIZE_RANGE_PK" PRIMARY KEY ("SIZE_RANGE_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_SIZE_RANGE_LU" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_SIZE_RANGE_LU" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_SIZE_RANGE_LU" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_SIZE_RANGE_LU" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_SIZE_RANGE_LU" MODIFY ("SIZE_HIGHER_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SOK_SIZE_RANGE_LU" MODIFY ("SIZE_LOWER_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SOK_SIZE_RANGE_LU" MODIFY ("SIZE_RANGE_CODE" NOT NULL ENABLE);
