--------------------------------------------------------
--  Constraints for Table SOK_ORDER_CONTENT
--------------------------------------------------------

  ALTER TABLE "SOK_ORDER_CONTENT" ADD CONSTRAINT "SOK_ORDER_CONTENT_PK" PRIMARY KEY ("PRODUCT_DETAIL_ID", "ORDER_ID")
  USING INDEX ENABLE;
  ALTER TABLE "SOK_ORDER_CONTENT" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER_CONTENT" MODIFY ("PRODUCT_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SOK_ORDER_CONTENT" MODIFY ("ORDER_PRODUCT_QUANTITY" NOT NULL ENABLE);
