--------------------------------------------------------
--  Constraints for Table SOK_PRODUCT_DETAIL_LU
--------------------------------------------------------

  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" ADD CONSTRAINT "SOK_PRODUCT_DETAIL_PK" PRIMARY KEY ("PRODUCT_DETAIL_ID")
  USING INDEX ENABLE;
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" ADD CHECK (product_detail_stock>= 0) ENABLE;
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("PRODUCT_DETAIL_STOCK" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("SEX_CODE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("SIZE_RANGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" MODIFY ("PRODUCT_DETAIL_ID" NOT NULL ENABLE);
