--------------------------------------------------------
--  Constraints for Table SOK_SEX_TYPE_LU
--------------------------------------------------------

  ALTER TABLE "SOK_SEX_TYPE_LU" ADD CONSTRAINT "SOK_SEX_TYPE_UK" UNIQUE ("SEX_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_SEX_TYPE_LU" ADD CONSTRAINT "SOK_SEX_TYPE_PK" PRIMARY KEY ("SEX_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_SEX_TYPE_LU" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_SEX_TYPE_LU" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_SEX_TYPE_LU" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_SEX_TYPE_LU" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_SEX_TYPE_LU" MODIFY ("SEX_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOK_SEX_TYPE_LU" MODIFY ("SEX_CODE" NOT NULL ENABLE);
