--------------------------------------------------------
--  Constraints for Table SOK_PRODUCT_PRICE_LU
--------------------------------------------------------

  ALTER TABLE "SOK_PRODUCT_PRICE_LU" ADD CONSTRAINT "SOK_PRODUCT_PRICE_PK" PRIMARY KEY ("PRODUCT_PRICE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SOK_PRODUCT_PRICE_LU" ADD CHECK (product_price_amount>0) ENABLE;
  ALTER TABLE "SOK_PRODUCT_PRICE_LU" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_PRICE_LU" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_PRICE_LU" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_PRICE_LU" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_PRICE_LU" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_PRICE_LU" MODIFY ("PRODUCT_PRICE_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "SOK_PRODUCT_PRICE_LU" MODIFY ("PRODUCT_PRICE_ID" NOT NULL ENABLE);
