--------------------------------------------------------
--  Ref Constraints for Table SOK_PRODUCT_DETAIL_LU
--------------------------------------------------------

  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" ADD CONSTRAINT "SOK_PRODUCT_DETAIL_PRODUCT_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "SOK_PRODUCT_LU" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" ADD CONSTRAINT "SOK_PRODUCT_DETAIL_SEX_TYPE_FK" FOREIGN KEY ("SEX_CODE")
	  REFERENCES "SOK_SEX_TYPE_LU" ("SEX_CODE") ENABLE;
  ALTER TABLE "SOK_PRODUCT_DETAIL_LU" ADD CONSTRAINT "SOK_PRODUCT_DETAIL_SIZE_FK" FOREIGN KEY ("SIZE_RANGE_CODE")
	  REFERENCES "SOK_SIZE_RANGE_LU" ("SIZE_RANGE_CODE") ENABLE;
