--------------------------------------------------------
--  Ref Constraints for Table SOK_ORDER_CONTENT
--------------------------------------------------------

  ALTER TABLE "SOK_ORDER_CONTENT" ADD CONSTRAINT "SOK_ORDER_CONTENT_ORDER_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SOK_ORDER" ("ORDER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SOK_ORDER_CONTENT" ADD CONSTRAINT "SOK_ORDER_CONT_PROD_DETAIL_FK" FOREIGN KEY ("PRODUCT_DETAIL_ID")
	  REFERENCES "SOK_PRODUCT_DETAIL_LU" ("PRODUCT_DETAIL_ID") ENABLE;
